name: Deploy to GCP

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 작동

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Excuting remote SSH commands using SSH key
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{secrets.HOST}}       # GCP 인스턴스의 외부 IP
        username: ${{secrets.USERNAME}} # GCP 인스턴스의 사용자 이름
        key: ${{secrets.SSH_KEY}}      # SSH 개인 키
        script: |
          # 코드 업데이트 및 배포
          cd /home/${{secrets.USERNAME}}/patturning-official
          git pull origin main  # 최신 코드 가져오기
          source venv/bin/activate
          nohup streamlit run app.py &  # Streamlit 앱 재시작
