name: Deploy to GCP

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 작동
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Excuting remote SSH commands using SSH key
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{secrets.HOST}}       # GCP 인스턴스의 외부 IP
        username: ${{secrets.USERNAME}} # GCP 인스턴스의 사용자 이름
        key: ${{secrets.SSH_KEY}}      # SSH 개인 키
        debug: true
        script: |
          cd /home/${{secrets.USERNAME}}/patturning-official
          git reset --hard
          git clean -fd
          git pull origin main
          source /home/${{secrets.USERNAME}}/streamlit_env/bin/activate 
          nohup streamlit run app.py &> streamlit.log &
